import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { BOMItem, CapacityInfo, CostSummary, WeightSummary, TankDimensions } from '@/types/tank';

interface ExportData {
  dimensions: TankDimensions;
  capacity: CapacityInfo;
  bomItems: BOMItem[];
  costSummary: CostSummary;
  weightSummary: WeightSummary;
}

export function exportToPDF(data: ExportData): void {
  const { dimensions, capacity, bomItems, costSummary, weightSummary } = data;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(0, 51, 102);
  doc.text('Al Muhaidib National Tanks', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('GRP Panel Tank - Bill of Materials', pageWidth / 2, 30, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 40);

  // Tank Dimensions
  doc.setFontSize(12);
  doc.setTextColor(0, 51, 102);
  doc.text('Tank Specifications', 14, 50);

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);

  const totalLength = dimensions.length1 + dimensions.length2 + dimensions.length3 + dimensions.length4;
  const specs = [
    `Width: ${dimensions.width}m`,
    `Length: ${totalLength}m`,
    `Height: ${dimensions.height}m`,
    `Nominal Capacity: ${capacity.nominal_capacity_m3} m³`,
    `Actual Capacity: ${capacity.actual_capacity_m3} m³`,
    `Partitions: ${capacity.num_partitions}`,
  ];

  let yPos = 58;
  specs.forEach((spec, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    doc.text(spec, 14 + col * 65, yPos + row * 6);
  });

  // BOM Table
  yPos = 78;
  doc.setFontSize(12);
  doc.setTextColor(0, 51, 102);
  doc.text('Bill of Materials', 14, yPos);

  // Group items by category
  const categories = [...new Set(bomItems.map(item => item.category))];

  const tableData = bomItems.map(item => [
    item.part_no,
    item.part_name || '-',
    item.quantity.toString(),
    `$${item.unit_price_usd.toFixed(2)}`,
    `$${item.total_price_usd.toFixed(2)}`,
    item.total_weight_kg > 0 ? `${item.total_weight_kg.toFixed(2)} kg` : '-',
  ]);

  autoTable(doc, {
    startY: yPos + 5,
    head: [['Part No', 'Description', 'Qty', 'Unit Price', 'Total', 'Weight']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [0, 51, 102],
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 7,
    },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: 50 },
      2: { cellWidth: 15, halign: 'center' },
      3: { cellWidth: 22, halign: 'right' },
      4: { cellWidth: 25, halign: 'right' },
      5: { cellWidth: 22, halign: 'right' },
    },
    margin: { left: 14, right: 14 },
  });

  // Get final Y position after table
  const finalY = (doc as any).lastAutoTable.finalY + 10;

  // Check if we need a new page for summary
  if (finalY > 250) {
    doc.addPage();
    yPos = 20;
  } else {
    yPos = finalY;
  }

  // Cost Summary
  doc.setFontSize(12);
  doc.setTextColor(0, 51, 102);
  doc.text('Cost Summary', 14, yPos);

  const costData = [
    ['Panels', `$${costSummary.panels.toFixed(2)}`],
    ['Steel Skid', `$${costSummary.steel_skid.toFixed(2)}`],
    ['Bolts & Nuts', `$${costSummary.bolts_nuts.toFixed(2)}`],
    ['External Reinforcing', `$${costSummary.external_reinforcing.toFixed(2)}`],
    ['Internal Reinforcing', `$${costSummary.internal_reinforcing.toFixed(2)}`],
    ['Tie Rods', `$${costSummary.internal_tie_rod.toFixed(2)}`],
    ['Accessories (ETC)', `$${costSummary.etc.toFixed(2)}`],
    ['Fittings', `$${costSummary.fittings.toFixed(2)}`],
  ];

  autoTable(doc, {
    startY: yPos + 5,
    body: costData,
    theme: 'plain',
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 30, halign: 'right' },
    },
    margin: { left: 14 },
  });

  // Total
  const costFinalY = (doc as any).lastAutoTable.finalY;
  doc.setFontSize(11);
  doc.setFont(undefined, 'bold');
  doc.text(`Total (USD): $${costSummary.total_usd.toFixed(2)}`, 14, costFinalY + 8);
  doc.text(`Total (SAR): ${costSummary.total_sar.toFixed(2)} SAR`, 14, costFinalY + 15);

  // Weight Summary
  doc.setFont(undefined, 'normal');
  doc.setFontSize(11);
  doc.text(`Total Weight: ${weightSummary.total_kg.toFixed(2)} kg`, 100, costFinalY + 8);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by GRP Panel Tank Configurator', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save
  const fileName = `Tank_BOM_${dimensions.width}x${totalLength}x${dimensions.height}_${new Date().toISOString().slice(0,10)}.pdf`;
  doc.save(fileName);
}
